### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'autoswitch'

### ISSUE THREAD

**Issue by HDhotdog** [dexman545/Fabric-Autoswitch#11]
Playing on 1.15.2 and using the autoswitch-1.8.1.jar. When trying to launch the game I get this error:

```
---- Minecraft Crash Report ----
// You're mean.

Time: 22.05.20 23:26
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'autoswitch'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:392)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoSuchFieldError: field_22223
	at autoswitch.MaterialHandler.<init>(MaterialHandler.java:106)
	at autoswitch.AutoSwitchLists.getToolTargetLists(AutoSwitchLists.java:47)
	at autoswitch.AutoSwitch.onInitializeClient(AutoSwitch.java:100)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1510/1690962912.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
```

**Comment by dexman545** [comment]
Should be fixed in 1.8.2.
Will be on CurseForge soon
