### ISSUE TITLE
Crash due to holding left click with an open hand in creative then clicking right click

### ISSUE THREAD

**Issue by Afrocntrik** [dexman545/Fabric-Autoswitch#20]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/18/20 3:08 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.class_2680 cannot be cast to net.minecraft.class_1297
	at autoswitch.util.TargetableUtil.getUseTarget(TargetableUtil.java:115)
	at autoswitch.TargetableUsable.populateToolSelection(TargetableUsable.java:300)
	at autoswitch.Targetable.populateToolLists(Targetable.java:97)
	at autoswitch.TargetableUsable.<init>(TargetableUsable.java:292)
	at autoswitch.Targetable.use(Targetable.java:69)
	at autoswitch.events.SwitchEvent$2.invoke(SwitchEvent.java:65)
	at autoswitch.events.Scheduler.lambda$execute$0(Scheduler.java:26)
	at autoswitch.events.Scheduler$$Lambda$6628/1729168492.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at autoswitch.events.Scheduler.execute(Scheduler.java:24)
	at autoswitch.AutoSwitch.lambda$onInitializeClient$0(AutoSwitch.java:120)
	at autoswitch.AutoSwitch$$Lambda$3663/647789084.onEndTick(Unknown Source)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$null$2(ClientTickEvents.java:65)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents$$Lambda$2308/1297666596.onEndTick(Unknown Source)
	at net.minecraft.class_310.handler$bgb000$onEndTick(class_310.java:7817)
	at net.minecraft.class_310.method_1574(class_310.java:1575)
	at net.minecraft.class_310.method_1523(class_310.java:994)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at autoswitch.util.TargetableUtil.getUseTarget(TargetableUtil.java:115)
	at autoswitch.TargetableUsable.populateToolSelection(TargetableUsable.java:300)
	at autoswitch.Targetable.populateToolLists(Targetable.java:97)
	at autoswitch.TargetableUsable.<init>(TargetableUsable.java:292)
	at autoswitch.Targetable.use(Targetable.java:69)
	at autoswitch.events.SwitchEvent$2.invoke(SwitchEvent.java:65)
	at autoswitch.events.Scheduler.lambda$execute$0(Scheduler.java:26)
	at autoswitch.events.Scheduler$$Lambda$6628/1729168492.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at autoswitch.events.Scheduler.execute(Scheduler.java:24)
	at autoswitch.AutoSwitch.lambda$onInitializeClient$0(AutoSwitch.java:120)
	at autoswitch.AutoSwitch$$Lambda$3663/647789084.onEndTick(Unknown Source)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$null$2(ClientTickEvents.java:65)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents$$Lambda$2308/1297666596.onEndTick(Unknown Source)
	at net.minecraft.class_310.handler$bgb000$onEndTick(class_310.java:7817)

-- Affected level --
Details:
	All players: 1 total; [class_746['Afrocntrik'/338, l='ClientLevel', x=322.30, y=120.23, z=172.30]]
	Chunk stats: Client Chunk Cache: 361, 195
	Level dimension: minecraft:overworld
	Level spawn location: World: (-26,68,45), Chunk: (at 6,4,13 in -2,2; contains blocks -32,0,32 to -17,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 10061 game time, 10061 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1393263936 bytes (1328 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.0.2+1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		aquarius: Aquarius 1.0.1
		artofalchemy: Art of Alchemy 1.0.0-rc2+1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		autoswitch: AutoSwitch 2.6.0
		blue_endless_jankson: jankson +
		cardinal-components: Cardinal Components API 2.4.1
		cardinal-components-base: Cardinal Components API (base) 2.4.1
		cardinal-components-block: Cardinal Components API (blocks) 2.4.1
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.1
		cardinal-components-entity: Cardinal Components API (entities) 2.4.1
		cardinal-components-item: Cardinal Components API (items) 2.4.1
		cardinal-components-level: Cardinal Components API (world saves) 2.4.1
		cardinal-components-util: Cardinal Components API (utilities) 2.4.1
		cardinal-components-world: Cardinal Components API (worlds) 2.4.1
		cavebiomes: Cave Biomes 0.2.3
		cinderscapes: Cinderscapes 1.0.5+build.36-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		crimsonmoon: Crimson Moon 1.1.0-1.16
		curioofundying: Curio of Undying 1.16.1-1.0
		curios: Curios API 1.16.1-0.2
		curiousshulkerboxes: Curious Shulker Boxes 1.16.1-1.0
		dataloader: Data Loader 2.1.0+mc1.16.1
		diggusmaximus: Diggus Maximus 1.2.11-1.16
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		economical_villager_trading: Economical Villager Trading 0.9.0-1+1.16.1
		experimentaway: ExperimentAway 1.0.0
		fabric: Fabric API 0.15.0+build.379-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a9774b0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+013e49d202
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		fiber: fiber 0.23.0-1
		flonters: Flonters 1.1.0+1.16.1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		illuminations: Illuminations 0.5.1
		jankson: Jankson 3.0.0+j1.2.0
		kirin: Kirin UI 1.6.4-1.16-rc1-1.16-SNAPSHOT
		kyrptconfig: Kytpt Config 1.0.4-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.7.1-pre.4
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.0.1+1.16.1
		libmultipart: LibMultiPart 0.4.0
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.4.0
		libnetworkstack: Lib Network Stack 0.4.0
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		mechanized: Mechanized 1.9.1
		minecraft: Minecraft 1.16.1
		minime_paperdoll: Player Mini-Me (Paper Doll) 1.0.4
		modmenu: Mod Menu 1.14.3+build.28
		mousewheelie: Mouse Wheelie 1.5.0+mc1.16.1
		nbtcrafting: NBT Crafting 2.0.0-beta.1+mc1.16.1
		netherited: Netherited 0.8.1
		netheritehorsearmor: Netherite Horse Armor 0.3.0
		notchify: Notchify 0.2.1
		notrample: No Trample 0.0.1
		org_aeonbits_owner_owner: owner 1.0.10
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		parchment: Parchment 1.0.2+1.15.2
		parry: Parry 1.0
		patchouli: Patchouli 1.16-38-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		presencefootsteps: Presence Footsteps r26+1.16-rc1
		reborncore: Reborn Core 4.3.2+build.49
		repurposed_structures: Repurposed Structures 1.2.1
		roughlyenoughitems: Roughly Enough Items 4.10.2
		rpgstats: RPGStats 2.0.3+1.16.1
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		silky_spawners: Silky Spawners 2.0.0+build.1-1.16
		simpledrawers: Simple Drawers 1.8.0-1.16.1
		simplexterrain: Simplex Terrain 0.6.4
		soaring-clouds: Soaring Clouds 1.1.0-1.16
		staticfov: Static FOV 1.0.1
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.3+build.72
		terraform: Terraform 2.1.7+build.31
		the_bumblezone: The Bumblezone - Fabric 1.16.1-2.0.1
		tinytweaks: TinyTweaks 1.0.11
		tweed: Tweed API 3.0.0-beta.9
		vanilla_parts: Vanilla Parts 1.1.3+1.16.1
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		voidfog: Void Fog 2.3.2+1.16-rc1
		wildworld: Wild World 1.2.3-1.16
		wolveswitharmor: Wolves With Armor 1.4.0-1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7262, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by dexman545** [comment]
Fixed in 2.7.0
