### ISSUE TITLE
Minecraft crashes on launch

### ISSUE THREAD

**Issue by Pandasaurus-Rex** [dexman545/Fabric-Autoswitch#41]
I get this error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'AutoSwitch API' (autoswitch-api) 2.0.0 with any version between 1.1.0 (inclusive) and 2- (exclusive).
Unmet dependency listing:
	 - Mod 'AutoSwitch' (autoswitch) 5.1.4 requires any version between 1.1.0 (inclusive) and 2- (exclusive) of mod 'AutoSwitch API' (autoswitch-api), but only the wrong version is present: 2.0.0!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I'm running the latest version from curseforge (autoswitch-5.1.4.jar)

**Comment by AliceDTRH** [comment]
Same here, some info:

Environment:
* File downloaded at: https://modrinth.com/mod/autoswitch/version/5.1.4
* OS: Linux
* Minecraft info: Minecraft 1.19 with Fabric Loader 0.14.8

<details>
<summary>Traceback</summary>

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'AutoSwitch API' (autoswitch-api) 2.0.0 with any version between 1.1.0 (inclusive) and 2- (exclusive).
Unmet dependency listing:
	 - Mod 'AutoSwitch' (autoswitch) 5.1.4 requires any version between 1.1.0 (inclusive) and 2- (exclusive) of mod 'AutoSwitch API' (autoswitch-api), but only the wrong version is present: 2.0.0!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


</details>

**Comment by dexman545** [comment]
This is what I get for updating from github...

Please downgrade to a previous version as a new release will be needed and will take a couple of days.
