### ISSUE TITLE
Minecraft crashes on launch

### ISSUE THREAD

**Issue by senkmen18** [dexman545/Fabric-Autoswitch#44]
I using a Quilt Loader
this is logs

```
[12:23:09] [main/INFO]: Loading Minecraft 1.19 with Quilt Loader 0.17.3
[12:23:10] [ForkJoinPool-1-worker-2/WARN]: Neither a fabric nor a quilt JAR at "C:\Users\Rasstegai\AppData\Roaming\PolyMC\instances\OneTOWN\.minecraft\mods\1.8.9.AutoUpdater-1.1.1.jar", ignoring
[12:23:10] [ForkJoinPool-1-worker-10/WARN]: Warnings for mod "inventorytabs"'s mod json:
- Version 0.9.beta-1.19.x does not respect SemVer -- comparison support is limited. "version" at  at line 4 column 31 path $.version
[12:23:10] [ForkJoinPool-1-worker-2/WARN]: Warnings for mod "jei"'s mod json:
- Version 11.1.1.239 has more than 3 version components, which may not be fully supported. "version" at  at line 4 column 26 path $.version
[12:23:10] [ForkJoinPool-1-worker-10/WARN]: Warnings for mod "ostoverhaul"'s mod json:
- Version 0.2.6.1 has more than 3 version components, which may not be fully supported. "version" at  at line 4 column 23 path $.version
[12:23:10] [main/ERROR]: Incompatible mod set!
org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'AutoSwitch' (autoswitch) v5.1.5-alpha.1:
Dependency for mod 'autoswitch' on fabric-client-tags-api-v1 versions [>=1.0.0] (0 valid options, 0 invalid options)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:214) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:141) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) [quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'AutoSwitch' (autoswitch) v5.1.5-alpha.1:
Dependency for mod 'autoswitch' on fabric-client-tags-api-v1 versions [>=1.0.0] (0 valid options, 0 invalid options)
	at org.quiltmc.loader.impl.solver.ModSolver.fallbackErrorDescription(ModSolver.java:615) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.solver.ModSolver.findCompatibleSet(ModSolver.java:244) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:432) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:223) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:212) ~[quilt-loader-0.17.3.jar:?]
	... 10 more
```

and a version a new.

**Comment by dexman545** [comment]
Update of install fabric api.

At this time, the only support quilt is getting is "I won't intentionally break it."
